accountsmgm/urls.py
from django.conf.urls import include, url, patterns

from . import views

urlpatterns = [
    url(r'^recover/$', views.recover, name='recover_page'),
    url(r'^new/$', views.new_account, name='get_new_page'),
    url(r'^$', views.login, name='login_page'),
]

dashboard/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = [
    url(r'^save-indexes/$', views.save_indexes, name='save_indexes'),
    url(r'^get-recorded-indexes/$', views.get_indexes, name='get_recorded_indexes'),
    url(r'^get-calculated-costs/$', views.get_calculated_costs, name='get_calculated_costs'),
    url(r'^$', views.main, name='main_page'),
]

getracker/urls.py
from django.conf.urls import include, url, patterns

from accountsmgm import urls as accountsmgm_urls
from dashboard import urls as dashboard_urls
from accountsmgm import views as accountsmgm_views

urlpatterns = [
    url(r'^accountsmgm/', include(accountsmgm_urls, namespace='accountsmgm')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^$', accountsmgm_views.login, name="login_page"),
]

templates/accountsmgm_base.html
{% extends 'template.html' %}

{% load static from staticfiles %}
{% load i18n %}
{% load url from future %}

{% block section_css %}
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/accountsmgm.css' %}" />
{% endblock %}

{% block section_js %}
    {{ block.super }}
    require(["dijit/layout/ContentPane", "dijit/layout/BorderContainer"]);
{% endblock %}

{% block pagebody %}
    <div data-dojo-type="dijit/layout/BorderContainer" class="container codes_container" data-dojo-props="gutters: true">
        <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'top'" id="header">
            {{ GL_APP_NAME|upper }} VER {{ GL_APP_VERSION }}
            <span id="top_menu">
                <button data-dojo-type="dijit/form/Button" data-dojo-id="loginBtn"
                        onclick="window.location.replace('{% url 'accountsmgm:login_page' %}')"
                        {% if activeMenu == 'login' %}disabled{% endif %}>
                            {% trans "Login" %}
                </button>
                <button data-dojo-type="dijit/form/Button" data-dojo-id="recoverBtn"
                        onclick="window.location.replace('{% url 'accountsmgm:recover_page' %}')"
                        {% if activeMenu == 'recover' %}disabled{% endif %}>
                            {% trans "Recover" %}
                </button>
                <button data-dojo-type="dijit/form/Button" data-dojo-id="getNewBtn"
                        onclick="window.location.replace('{% url 'accountsmgm:get_new_page' %}')"
                        {% if activeMenu == 'getnew' %}disabled{% endif %}>
                            {% trans "Get New" %}
                </button>
            </span>
        </div>

        <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center'" id="main_pane">
            {% block maincontent %}{% endblock %}
        </div>

        <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'bottom'" align="right" id="footer">
            <span>Copyright &copy; 2015 - 2016 {{ GL_APP_AUTHOR }}</span>
        </div>
    </div>
{% endblock %}

templates/dashboard_base.html
{% extends 'template.html' %}

{% load static from staticfiles %}
{% load i18n %}
{% load url from future %}

{% block section_js %}
    {{ block.super }}
    require(["dijit/layout/ContentPane", "dijit/layout/BorderContainer"]);
{% endblock %}

{% block pagebody %}
    <div data-dojo-type="dijit/layout/BorderContainer" class="container codes_container" data-dojo-props="gutters: true">
        <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'top'" id="header">
            DASHBOARD - {{ GL_APP_NAME|upper }} VER {{ GL_APP_VERSION }}
            <span id="top_menu">
                <span>{% trans 'CODE' %}: {{ logged_code }}</span>
                <button data-dojo-type="dijit/form/Button" data-dojo-id="logoutBtn"
                        onclick="window.location.replace('{% url 'accountsmgm:login_page' %}')">
                        {% trans "Logout" %}
                </button>
            </span>
        </div>

        <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center'" id="main_pane">
            {% block maincontent %}{% endblock %}
        </div>

        <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'bottom'" align="right" id="footer">
            <span>Copyright &copy; 2015 - 2016 {{ GL_APP_AUTHOR }}</span>
        </div>
    </div>
{% endblock %}

templates/template.html
<!DOCTYPE html>
{% load static from staticfiles %}{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GETracker-{% block pagetitle %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'dijit/themes/claro/claro.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'dijit/themes/claro/document.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <link href='http://fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'>

    <script>
    var dojoConfig = {
        async: true,
        parseOnLoad: false,
        isDebug: true,
        // locale: 'nl-nl',
        locale: 'en-GB',
        has: {
            "dojo-firebug": true,
            "dojo-debug-messages": true
        },
        map: {
            // Instead of having to type "dojo/domReady!", we just want "ready!" instead
            "*": {
                ready: "dojo/domReady"
            }
        }
    };

    var overlay;
    </script>

    {% block section_css %}{% endblock %}
    {% block subsection_css %}{% endblock %}
</head>
<body class="claro">
    <div id="loadingOverlay" class="loadingMessage pageOverlay"></div>

    <script src="{% static 'dojo/dojo.js' %}"></script>

    <script>
    // $.noConflict(); // if jquery is added

    require(["dojo/_base/declare", "dojo/dom", "dojo/dom-style", "dojo/_base/fx"],
    function(declare, dom, domStyle, fx){
        var Overlay = declare(null, {
            overlayNode: null,
            constructor: function() {
                this.overlayNode = dom.byId("loadingOverlay");
            },
            endLoading: function() {
              <!--
              fx.fadeOut({
                node: this.overlayNode,
                onEnd: function(node){
                    domStyle.set(node, 'display', 'none');
                }
              }).play();
              -->
              domStyle.set(this.overlayNode,'display','none');
            }
        });

        overlay = new Overlay();
    });

    </script>

    {% block pagebody %}{% endblock %}

    <script>
    {% block section_js %}
        require(["/static/js/getracker.js"]);
        require(["dojo/parser", "dojo/ready"], function(parser, ready){
            ready(function(){
                parser.parse().then(function() { overlay.endLoading(); });
            });
        });
    {% endblock %}
    </script>

    {% block external_js %}{% endblock %}
</body>
</html>